<?php

namespace App\Controller;

use App\Entity\Funcionario;
use App\Form\FuncionarioType;
use App\Repository\FuncionarioRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


/**
 * @Route("/funcionario")
 */
class FuncionarioController extends Controller
{
    /**
     * @Route("/", name="funcionario_index", methods="GET")
     */
    public function index(FuncionarioRepository $funcionarioRepository): Response
    {
        return $this->render('funcionario/index.html.twig', ['funcionarios' => $funcionarioRepository->findAll()]);
    }
    /**
     * @Route("/new", name="funcionario_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $funcionario = new Funcionario();
        $form = $this->createForm(FuncionarioType::class, $funcionario);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $funcionario->setStatus('A');

            $imagem = $funcionario->getImagemDocumento();
            $nome_imagem = $this->generateUniqueFileName().".".$imagem->guessExtension();
            $imagem->move($this->getParameter('caminho_imagem'), $nome_imagem);
            $funcionario->setImagemDocumento($nome_imagem);

            $funcionario->calculaLiquido();

            $em->persist($funcionario);
            $em->flush();

            $this->addFlash('success', "Funcionário foi salvo com sucesso!");
            return $this->redirectToRoute('funcionario_index');

        }
        return $this->render('funcionario/new.html.twig', [
            'funcionario' => $funcionario,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/{id}", name="funcionario_show", methods="GET")
     */
    public function show(Funcionario $funcionario): Response
    {
        return $this->render('funcionario/show.html.twig', ['funcionario' => $funcionario]);
    }
    /**
     * @Route("/{id}/edit", name="funcionario_edit", methods="GET|POST")
     */
    public function edit(Request $request, Funcionario $funcionario, FuncionarioRepository $funcionarioRepository): Response
    {
        $form = $this->createForm(FuncionarioType::class, $funcionario);
        /** @var File $file */
        $img_doc = $funcionario->getImagemDocumento();
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
           $imagem = $form->get('imagem_documento')->getData();

           if(null != $imagem) {
               $nome_imagem = $this->generateUniqueFileName() . "." . $imagem->guessExtension();
               $imagem->move($this->getParameter('caminho_imagem'), $nome_imagem);
               $funcionario->setImagemDocumento($nome_imagem);

           }elseif(null == $funcionario->getImagemDocumento()) {
               $funcionario->setImagemDocumento($img_doc);
           };


            $funcionario->calculaLiquido();
            $this->getDoctrine()->getManager()->flush();

            $this->addFlash('success', "Funcionário foi editado com sucesso!");
            return $this->redirectToRoute('funcionario_index');
        };

        return $this->render('funcionario/edit.html.twig', [
            'funcionario' => $funcionario,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="funcionario_delete", methods="DELETE")
     */
    public function delete(Request $request, Funcionario $funcionario): Response
    {
        if ($this->isCsrfTokenValid('delete'.$funcionario->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($funcionario);
            $em->flush();
        }

        $this->addFlash('success', "Funcionário foi removido com sucesso!");
        return $this->redirectToRoute('funcionario_index');
    }
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}